// Code generated by go-obfuscate; DO NOT EDIT.
// Copyright (c) 2026 Prilog. MIT; see LICENSE.
package prilog

import (
	"context"
	"errors"
	"fmt"
	"io"
	stdlog "log"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"runtime"
	"runtime/debug"
	"strings"
	"sync"
	"time"

	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	otellog "go.opentelemetry.io/otel/log"
	logglobal "go.opentelemetry.io/otel/log/global"
	"go.opentelemetry.io/otel/propagation"
	logSDK "go.opentelemetry.io/otel/sdk/log"
	"go.opentelemetry.io/otel/sdk/resource"
	traceSDK "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

type Config struct {
	DSN, ServiceName, Environment, Release string
	LogHandler                             slog.Handler
}
type Monitor struct {
	_p0001         *traceSDK.TracerProvider
	_p0002         *logSDK.LoggerProvider
	_p0003         otellog.Logger
	_p0004, _p0005 *slog.Logger
	_p0006         sync.Once
	_p0007         error
	_p0008         io.Writer
	_p0009         int
}

func Init(_p000a context.Context, _p000b Config) (*Monitor, error) {
	if _p000c := os.Getenv(_p0049[0x0]); _p000c != "" {
		_p000b.DSN = _p000c
	}
	if _p000b.DSN == "" {
		return &Monitor{}, nil
	}
	_p000d, _p000e := url.Parse(_p000b.DSN)
	if _p000e != nil || _p000d.Host == "" || _p000d.User == nil || (_p000d.Scheme != _p0049[0x1] && _p000d.Scheme != _p0049[0x2]) || _p000d.RawQuery != "" || _p000d.Fragment != "" {
		return nil, fmt.Errorf("invalid Prilog monitoring DSN")
	}
	if _, _p000f := _p000d.User.Password(); _p000f {
		return nil, fmt.Errorf("monitoring DSN must not contain a password")
	}
	_p0010 := map[string]string{_p0049[0x3]: _p000d.User.Username()}
	_p000d.User = nil
	_p0011 := strings.TrimSuffix(_p000d.String(), _p0049[0x4])
	if _p0012 := os.Getenv(_p0049[0x5]); _p0012 != "" {
		_p0011 = strings.TrimSuffix(_p0012, _p0049[0x4])
	}
	if _p0013 := os.Getenv(_p0049[0x6]); _p0013 != "" {
		_p000b.ServiceName = _p0013
	}
	if _p000b.ServiceName == "" {
		_p000b.ServiceName = _p0049[0x7]
	}
	_p0014 := resource.NewWithAttributes("", attribute.String(_p0049[0x8], _p000b.ServiceName), attribute.String(_p0049[0x9], _p000b.Environment), attribute.String(_p0049[0xa], _p000b.Release), attribute.String(_p0049[0xb], _p0049[0xc]))
	_p0015, _p000e := otlptracehttp.New(_p000a, otlptracehttp.WithEndpointURL(_p0011+_p0049[0xd]), otlptracehttp.WithHeaders(_p0010), otlptracehttp.WithTimeout(5*time.Second))
	if _p000e != nil {
		return nil, _p000e
	}
	_p0016, _p000e := otlploghttp.New(_p000a, otlploghttp.WithEndpointURL(_p0011+_p0049[0xe]), otlploghttp.WithHeaders(_p0010), otlploghttp.WithTimeout(5*time.Second))
	if _p000e != nil {
		_ = _p0015.Shutdown(_p000a)
		return nil, _p000e
	}
	_p0017 := &Monitor{_p0001: traceSDK.NewTracerProvider(traceSDK.WithResource(_p0014), traceSDK.WithBatcher(_p0015)), _p0002: logSDK.NewLoggerProvider(logSDK.WithResource(_p0014), logSDK.WithProcessor(logSDK.NewBatchProcessor(_p0016)))}
	_p0017._p0003 = _p0017._p0002.Logger(_p0049[0xf])
	logglobal.SetLoggerProvider(_p0017._p0002)
	otel.SetTracerProvider(_p0017._p0001)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	_p0017._p0004 = slog.Default()
	_p0017._p0008, _p0017._p0009 = stdlog.Writer(), stdlog.Flags()
	_p0018 := _p000b.LogHandler
	if _p0018 == nil {
		_p0018 = slog.NewTextHandler(_p0017._p0008, nil)
	}
	_p0017._p0005 = slog.New(&_p0034{_p0035: _p0018, _p0036: _p0017._p0003})
	slog.SetDefault(_p0017._p0005)
	_p0019, _p001a := otel.Tracer(_p0049[0xf]).Start(_p000a, _p0049[0x10])
	slog.InfoContext(_p0019, _p0049[0x11], _p0049[0x10], true)
	_p001a.End()
	return _p0017, nil
}

func (_p001b *Monitor) Shutdown(_p001c context.Context) error {
	if _p001b == nil || _p001b._p0001 == nil {
		return nil
	}
	_p001b._p0006.Do(func() {
		if slog.Default() == _p001b._p0005 {
			slog.SetDefault(_p001b._p0004)
			stdlog.SetOutput(_p001b._p0008)
			stdlog.SetFlags(_p001b._p0009)
		}
		_p001b._p0007 = errors.Join(_p001b._p0002.Shutdown(_p001c), _p001b._p0001.Shutdown(_p001c))
	})
	return _p001b._p0007
}

func (_p001d *Monitor) CaptureError(_p001e context.Context, _p001f error) {
	if _p001f == nil || _p001d == nil || _p001d._p0001 == nil {
		return
	}
	_p0020 := trace.SpanFromContext(_p001e)
	if !_p0020.SpanContext().IsValid() {
		_p001e, _p0020 = _p001d._p0001.Tracer(_p0049[0xf]).Start(_p001e, _p0049[0x12])
		defer _p0020.End()
	}
	_p0020.RecordError(_p001f, trace.WithStackTrace(true))
	_p0020.SetStatus(codes.Error, _p001f.Error())
	var _p0021 otellog.Record
	_p0021.SetTimestamp(time.Now())
	_p0021.SetSeverity(otellog.SeverityError)
	_p0021.SetSeverityText(_p0049[0x13])
	_p0021.SetBody(otellog.StringValue(_p001f.Error()))
	_p0021.AddAttributes(otellog.String(_p0049[0x14], fmt.Sprintf("%T", _p001f)), otellog.String(_p0049[0x15], _p001f.Error()), otellog.String(_p0049[0x16], string(debug.Stack())))
	_p001d._p0003.Emit(_p001e, _p0021)
}

func (_p0022 *Monitor) Recover(_p0023 context.Context) {
	if _p0024 := recover(); _p0024 != nil {
		if _p0022 != nil && _p0022._p0001 != nil {
			_p0025, _p0026 := _p0022._p0001.Tracer(_p0049[0xf]).Start(_p0023, _p0049[0x17])
			_p0022.CaptureError(_p0025, fmt.Errorf("panic: %v", _p0024))
			_p0026.End()
			_p0027, _p0028 := context.WithTimeout(context.WithoutCancel(_p0023), 3*time.Second)
			_ = _p0022._p0002.ForceFlush(_p0027)
			_ = _p0022._p0001.ForceFlush(_p0027)
			_p0028()
		}
		panic(_p0024)
	}
}

func (_p0029 *Monitor) Run(_p002a context.Context, _p002b string, _p002c func(context.Context) error) error {
	_p002a, _p002d := otel.Tracer(_p0049[0xf]).Start(_p002a, _p002b)
	defer _p002d.End()
	defer _p0029.Recover(_p002a)
	_p002e := _p002c(_p002a)
	if _p002e != nil {
		_p0029.CaptureError(_p002a, _p002e)
	}
	return _p002e
}

func (_p002f *Monitor) HTTPHandler(_p0030 string, _p0031 http.Handler) http.Handler {
	return otelhttp.NewHandler(http.HandlerFunc(func(_p0032 http.ResponseWriter, _p0033 *http.Request) {
		defer _p002f.Recover(_p0033.Context())
		_p0031.ServeHTTP(_p0032, _p0033)
	}), _p0030)
}

type _p0034 struct {
	_p0035 slog.Handler
	_p0036 otellog.Logger
	_p0037 []otellog.KeyValue
	_p0038 string
}

func (_p0039 *_p0034) Enabled(_p003a context.Context, _p003b slog.Level) bool {
	return _p003b >= slog.LevelInfo || _p0039._p0035.Enabled(_p003a, _p003b)
}
func (_p003c *_p0034) Handle(_p003d context.Context, _p003e slog.Record) error {
	var _p003f otellog.Record
	_p003f.SetTimestamp(_p003e.Time)
	_p003f.SetSeverity(otellog.Severity(int(_p003e.Level) + 9))
	_p003f.SetSeverityText(_p003e.Level.String())
	_p003f.SetBody(otellog.StringValue(_p003e.Message))
	_p003f.AddAttributes(_p003c._p0037...)
	if _p003e.PC != 0 {
		_p0040, _ := runtime.CallersFrames([]uintptr{_p003e.PC}).Next()
		_p003f.AddAttributes(otellog.String(_p0049[0x18], _p0040.File), otellog.String(_p0049[0x19], _p0040.Function), otellog.Int(_p0049[0x1a], _p0040.Line))
	}
	_p003e.Attrs(func(_p0041 slog.Attr) bool {
		_p003f.AddAttributes(otellog.String(_p003c._p0038+_p0041.Key, _p0041.Value.String()))
		return true
	})
	_p003c._p0036.Emit(_p003d, _p003f)
	if _p003c._p0035.Enabled(_p003d, _p003e.Level) {
		return _p003c._p0035.Handle(_p003d, _p003e)
	}
	return nil
}
func (_p0042 *_p0034) WithAttrs(_p0043 []slog.Attr) slog.Handler {
	_p0044 := *_p0042
	_p0044._p0035 = _p0042._p0035.WithAttrs(_p0043)
	_p0044._p0037 = append([]otellog.KeyValue{}, _p0042._p0037...)
	for _, _p0045 := range _p0043 {
		_p0044._p0037 = append(_p0044._p0037, otellog.String(_p0042._p0038+_p0045.Key, _p0045.Value.String()))
	}
	return &_p0044
}
func (_p0046 *_p0034) WithGroup(_p0047 string) slog.Handler {
	_p0048 := *_p0046
	_p0048._p0035 = _p0046._p0035.WithGroup(_p0047)
	if _p0047 != "" {
		_p0048._p0038 += _p0047 + _p0049[0x1b]
	}
	return &_p0048
}

var _p0049 = [...]string{
	_p004a([]byte{0xf7, 0xf5, 0xee, 0xeb, 0xe8, 0xe0, 0xf8, 0xe3, 0xf4, 0xe9}),
	_p004a([]byte{0xcf, 0xd3, 0xd3, 0xd7, 0xd4}),
	_p004a([]byte{0xcf, 0xd3, 0xd3, 0xd7}),
	_p004a([]byte{0xff, 0x8a, 0xf7, 0xd5, 0xce, 0xcb, 0xc8, 0xc0, 0x8a, 0xe8, 0xf3, 0xeb, 0xf7, 0x8a, 0xf3, 0xc8, 0xcc, 0xc2, 0xc9}),
	_p004a([]byte{0x88}),
	_p004a([]byte{0xe8, 0xf3, 0xe2, 0xeb, 0xf8, 0xe2, 0xff, 0xf7, 0xe8, 0xf5, 0xf3, 0xe2, 0xf5, 0xf8, 0xe8, 0xf3, 0xeb, 0xf7, 0xf8, 0xe2, 0xe9, 0xe3, 0xf7, 0xe8, 0xee, 0xe9, 0xf3}),
	_p004a([]byte{0xe8, 0xf3, 0xe2, 0xeb, 0xf8, 0xf4, 0xe2, 0xf5, 0xf1, 0xee, 0xe4, 0xe2, 0xf8, 0xe9, 0xe6, 0xea, 0xe2}),
	_p004a([]byte{0xc6, 0xd7, 0xd7, 0xcb, 0xce, 0xc4, 0xc6, 0xd3, 0xce, 0xc8, 0xc9}),
	_p004a([]byte{0xd4, 0xc2, 0xd5, 0xd1, 0xce, 0xc4, 0xc2, 0x89, 0xc9, 0xc6, 0xca, 0xc2}),
	_p004a([]byte{0xc3, 0xc2, 0xd7, 0xcb, 0xc8, 0xde, 0xca, 0xc2, 0xc9, 0xd3, 0x89, 0xc2, 0xc9, 0xd1, 0xce, 0xd5, 0xc8, 0xc9, 0xca, 0xc2, 0xc9, 0xd3, 0x89, 0xc9, 0xc6, 0xca, 0xc2}),
	_p004a([]byte{0xd4, 0xc2, 0xd5, 0xd1, 0xce, 0xc4, 0xc2, 0x89, 0xd1, 0xc2, 0xd5, 0xd4, 0xce, 0xc8, 0xc9}),
	_p004a([]byte{0xd7, 0xd5, 0xce, 0xcb, 0xc8, 0xc0, 0x89, 0xd4, 0xc3, 0xcc, 0x89, 0xd1, 0xc2, 0xd5, 0xd4, 0xce, 0xc8, 0xc9}),
	_p004a([]byte{0x97, 0x89, 0x96, 0x89, 0x97}),
	_p004a([]byte{0x88, 0xd1, 0x96, 0x88, 0xd3, 0xd5, 0xc6, 0xc4, 0xc2, 0xd4}),
	_p004a([]byte{0x88, 0xd1, 0x96, 0x88, 0xcb, 0xc8, 0xc0, 0xd4}),
	_p004a([]byte{0xd7, 0xd5, 0xce, 0xcb, 0xc8, 0xc0, 0x89, 0xca, 0xc8, 0xc9, 0xce, 0xd3, 0xc8, 0xd5, 0xce, 0xc9, 0xc0}),
	_p004a([]byte{0xd7, 0xd5, 0xce, 0xcb, 0xc8, 0xc0, 0x89, 0xd4, 0xd3, 0xc6, 0xd5, 0xd3, 0xd2, 0xd7}),
	_p004a([]byte{0xf7, 0xd5, 0xce, 0xcb, 0xc8, 0xc0, 0x87, 0xca, 0xc8, 0xc9, 0xce, 0xd3, 0xc8, 0xd5, 0xce, 0xc9, 0xc0, 0x87, 0xce, 0xc9, 0xce, 0xd3, 0xce, 0xc6, 0xcb, 0xce, 0xdd, 0xc2, 0xc3}),
	_p004a([]byte{0xc2, 0xdf, 0xc4, 0xc2, 0xd7, 0xd3, 0xce, 0xc8, 0xc9}),
	_p004a([]byte{0xe2, 0xf5, 0xf5, 0xe8, 0xf5}),
	_p004a([]byte{0xc2, 0xdf, 0xc4, 0xc2, 0xd7, 0xd3, 0xce, 0xc8, 0xc9, 0x89, 0xd3, 0xde, 0xd7, 0xc2}),
	_p004a([]byte{0xc2, 0xdf, 0xc4, 0xc2, 0xd7, 0xd3, 0xce, 0xc8, 0xc9, 0x89, 0xca, 0xc2, 0xd4, 0xd4, 0xc6, 0xc0, 0xc2}),
	_p004a([]byte{0xc2, 0xdf, 0xc4, 0xc2, 0xd7, 0xd3, 0xce, 0xc8, 0xc9, 0x89, 0xd4, 0xd3, 0xc6, 0xc4, 0xcc, 0xd3, 0xd5, 0xc6, 0xc4, 0xc2}),
	_p004a([]byte{0xd7, 0xc6, 0xc9, 0xce, 0xc4}),
	_p004a([]byte{0xc4, 0xc8, 0xc3, 0xc2, 0x89, 0xc1, 0xce, 0xcb, 0xc2, 0x89, 0xd7, 0xc6, 0xd3, 0xcf}),
	_p004a([]byte{0xc4, 0xc8, 0xc3, 0xc2, 0x89, 0xc1, 0xd2, 0xc9, 0xc4, 0xd3, 0xce, 0xc8, 0xc9, 0x89, 0xc9, 0xc6, 0xca, 0xc2}),
	_p004a([]byte{0xc4, 0xc8, 0xc3, 0xc2, 0x89, 0xcb, 0xce, 0xc9, 0xc2, 0x89, 0xc9, 0xd2, 0xca, 0xc5, 0xc2, 0xd5}),
	_p004a([]byte{0x89}),
}

func _p004a(v []byte) string {
	for i := range v {
		v[i] ^= 0xa7
	}
	return string(v)
}
